/* ============================================================
   Study Live — strings.js
   UI dictionaries: ar (RTL, default), ru, en.
   Add a language: copy a block, translate, register in SL.LANGS.
   ============================================================ */
(function (root) {
  'use strict';

  var SL = (root.SL = root.SL || {});

  SL.LANGS = [
    { code: 'ar', native: 'العربية', dir: 'rtl' },
    { code: 'ru', native: 'Русский', dir: 'ltr' },
    { code: 'en', native: 'English', dir: 'ltr' },
  ];

  SL.STRINGS = {
    ar: {
      'app.tagline': 'دفترك الجامعي الرقمي — مهامك وملاحظاتك وفصولك في مكان واحد',

      'nav.overview': 'الرئيسية',
      'nav.tasks': 'المهام',
      'nav.notes': 'الملاحظات',
      'nav.stats': 'الإحصائيات',
      'nav.places': 'المواقع',
      'nav.teachers': 'الأساتذة',
      'nav.contacts': 'جهاتي',
      'nav.vault': 'الحسابات',
      'nav.profile': 'ملفي',

      'v.title': 'كلمات السر والحسابات',
      'v.setupTitle': 'إنشاء قفل الصفحة',
      'v.setupHint': 'اختر رمزًا من 4 أرقام واكتب تلميحة — التلميحة وحدها تتيح لك تغيير الرمز لاحقًا من «ملفي».',
      'v.pin': 'الرمز (4 أرقام)',
      'v.pinConfirm': 'تأكيد الرمز',
      'v.hint': 'التلميحة',
      'v.hintPh': 'جملة أو كلمة أو أرقام — فقط أنت تعرفها',
      'v.create': 'إنشاء القفل',
      'v.pinMismatch': 'الرمزان غير متطابقين',
      'v.need4': 'أدخل 4 أرقام',
      'v.unlockTitle': 'الصفحة مقفلة',
      'v.unlockSub': 'أدخل الرمز المكوّن من 4 أرقام لعرض حساباتك',
      'v.unlock': 'فتح',
      'v.wrongPin': 'الرمز غير صحيح — حاول مجددًا',
      'v.lockedOut': 'محاولات كثيرة خاطئة — انتظر {time} ثم حاول مجددًا',
      'v.lockBtn': 'قفل الصفحة',
      'v.add': 'إضافة حساب',
      'v.editTitle': 'تعديل الحساب',
      'v.entryTitle': 'العنوان',
      'v.entryTitlePh': 'مثال: حساب الجامعة',
      'v.username': 'اسم الحساب (اختياري)',
      'v.usernamePh': 'مثال: yousef.m2026',
      'v.url': 'رابط الموقع/البرنامج (اختياري)',
      'v.urlPh': 'https://…',
      'v.password': 'كلمة السر',
      'v.desc': 'وصف كلمة السر (اختياري)',
      'v.descPh': 'مثال: نفس رمز هاتفي',
      'v.empty': 'لا حسابات محفوظة بعد',
      'v.emptyHint': 'أضف أول حساب بكلمة سره — سيبقى مخفيًا خلف رمزك.',
      'v.deleteQ': 'حذف حساب «{name}»؟',
      'v.deleteHint': 'لا يمكن التراجع عن حذف كلمة السر.',
      'v.copied': 'نُسخت كلمة السر',
      'v.copyFail': 'تعذّر النسخ — انسخها يدويًا بعد الإظهار',
      'v.security': 'محمي برمزك على هذا الجهاز — البيانات لا تغادر متصفحك.',
      'v.searchPh': 'ابحث في الحسابات…',
      'nav.tasks': 'المهام',
      'nav.notes': 'الملاحظات',
      'nav.stats': 'الإحصائيات',
      'nav.profile': 'ملفي',

      'sh.ratio': 'نسبة الإنجاز',
      'sh.done': 'منجزة',
      'sh.notDone': 'غير منجزة',
      'sh.busiestDays': 'أكثر الأيام مهامًا',
      'sh.topSubjects': 'أكثر المواد مهامًا',
      'sh.mostMissed': 'أكثر المواد تفويتًا',
      'sh.standing': 'وضعي مع المواد',
      'sh.standingHint': 'حرّك المؤشر لكل مادة: أحمر = صعبة عليّ، أخضر = أتمكن منها. كل تغيير يُسجّل بتاريخه.',
      'sh.hard': 'صعبة عليّ',
      'sh.good': 'أتمكن منها',
      'sh.hardest': 'أصعب المواد عليّ',
      'sh.noStanding': 'لم تسجّل أي مؤشر بعد — حرّك المؤشرات في الأعلى.',
      'sh.improved': 'تحسّنت',
      'sh.declined': 'تراجعت',
      'sh.unchanged': 'لم تتغير بعد',
      'sh.lastChanged': 'آخر تحديث: {date}',
      'sh.noTasks': 'لا مهام بعد لتظهر الإحصائيات',
      'sh.noTasksHint': 'أضف مهامك وسنجمع لك الأرقام هنا تلقائيًا.',
      'sh.noSubjects': 'أضف موادك أولًا من صفحة المهام أو الملف الشخصي.',
      'sh.ofTotal': 'من {n}',
      'sh.summary': 'أنجزت {done} من {total} مهمة',

      'ov.gMorning': 'صباح الخير',
      'ov.gAfternoon': 'طاب يومك',
      'ov.gEvening': 'مساء الخير',
      'ov.statsToday': 'مهام اليوم',
      'ov.statsDone': 'أُنجزت اليوم',
      'ov.statsBacklog': 'التراكمات',
      'ov.statsNotes': 'الملاحظات',
      'ov.week': 'قادم هذا الأسبوع',
      'ov.weekEmpty': 'لا مهام في الأيام السبعة القادمة',

      'a.save': 'حفظ',
      'a.cancel': 'إلغاء',
      'a.delete': 'حذف',
      'a.edit': 'تعديل',
      'a.add': 'إضافة',
      'a.close': 'إغلاق',
      'a.done': 'تم',
      'a.today': 'اليوم',
      'a.none': 'بدون',
      'a.all': 'الكل',
      'a.search': 'بحث',
      'a.create': 'إنشاء',

      'hdr.lang': 'اللغة',
      'hdr.theme': 'الوضع',

      'ob.welcome': 'أهلًا بك في Study Live',
      'ob.tag': 'نظّم دراستك: مهام بالأيام، ملاحظات بموادك، وفصولك الدراسية.',
      'ob.lang': 'اختر اللغة',
      'ob.theme': 'المظهر',
      'ob.light': 'فاتح',
      'ob.dark': 'مضلم',
      'ob.start': 'لنبدأ',

      't.title': 'المهام',
      't.add': 'إضافة مهمة',
      't.modeDay': 'مهام اليوم',
      't.modeAll': 'كل المهام',
      't.groupBacklog': 'التراكمات',
      't.groupUpcoming': 'القادمة',
      't.groupDone': 'المنجزة',
      't.backlogEmpty': 'لا تراكمات — كل شيء تحت السيطرة',
      't.upcomingEmpty': 'لا مهام قادمة',
      't.doneEmpty': 'لا مهام منجزة بعد',
      't.emptyAll': 'لا مهام بعد',
      't.emptyAllHint': 'اضغط زر + لإضافة أول مهمة — يمكنك تحديد أي يوم حتى الماضي.',
      't.edit': 'تعديل المهمة',
      't.taskTitle': 'عنوان المهمة',
      't.taskTitlePh': 'مثال: مراجعة محاضرة الإحصاء',
      't.desc': 'الوصف (اختياري)',
      't.descPh': 'تفاصيل إضافية: صفحات، مراجع، ملاحظات…',
      't.date': 'اليوم',
      't.difficulty': 'الصعوبة',
      't.diffHard': 'صعبة',
      't.diffEasy': 'سهلة',
      't.diffLight': 'بسيطة',
      't.subject': 'المادة',
      't.noSubject': 'بدون مادة',
      't.subjectsBtn': 'المواد',
      't.markAllDone': 'إنجاز الكل',
      't.enableProgress': 'تفعيل التقدم',
      't.progress': 'التقدم',
      't.emptyDay': 'لا مهام في هذا اليوم',
      't.emptyDayHint': 'اضغط زر + لإضافة أول مهمة.',
      't.count': '{n} مهمة',
      't.agNoTasks': 'لا مهام',
      't.overdue': 'متأخرة',
      't.confirmDel': 'حذف هذه المهمة؟',
      't.deleteQ': 'حذف هذه المهمة؟',

      'pl.add': 'إضافة مكان جديد',
      'pl.editTitle': 'تعديل المكان',
      'pl.name': 'اسم المكان',
      'pl.namePh': 'مثال: مكتبة الجامعة الرئيسية',
      'pl.desc': 'الوصف (اختياري)',
      'pl.descPh': 'ملاحظات عن هذا المكان...',
      'pl.color': 'لون العلامة',
      'pl.nameRequired': 'يرجى إدخال اسم المكان',
      'pl.search': 'ابحث عن مكان...',
      'pl.searchBtn': 'بحث',
      'pl.useGps': 'استخدام موقعي الحالي',
      'pl.gpsError': 'تعذر تحديد الموقع',
  'pl.gpsDenied': 'تم رفض إذن الموقع — اضغط أيقونة القفل/ⓘ بجانب العنوان في المتصفح، اسمح بالموقع، ثم أعد المحاولة',
  'pl.gpsUnavailable': 'الجهاز لا يستطيع تحديد موقعك — فعّل خدمة الموقع (Location) من إعدادات Windows',
  'pl.gpsTimeout': 'انتهت مهلة تحديد الموقع — تأكد من اتصال الإنترنت وحاول مجدداً',
  'pl.gpsUnsupported': 'متصفحك لا يدعم تحديد الموقع الجغرافي',
  'pl.gpsDone': 'تم تعبئة الإحداثيات من موقعك الحالي',
  'pl.locate': 'إظهار موقعي على الخريطة',
  'pl.locating': 'جارٍ تحديد موقعك…',
  'pl.located': 'أنت هنا',
      'pl.deleteQ': 'حذف "{name}" نهائياً؟',

      'th.title': 'الأساتذة والتقييمات',
      'th.add': 'إضافة أستاذ',
      'th.edit': 'تعديل الأستاذ',
      'th.name': 'اسم الأستاذ',
      'th.namePh': 'مثال: أ. محمد العلي',
      'th.subject': 'المادة',
      'th.noSubject': 'بدون مادة',
      'th.subjectPh': 'المادة التي يدرّسها',
      'th.photo': 'صورة الأستاذ',
      'th.addPhoto': 'إضافة صورة',
      'th.changePhoto': 'تغيير الصورة',
      'th.removePhoto': 'إزالة الصورة',
      'th.rate': 'قيّم',
      'th.rateTitle': 'تقييم الأستاذ',
      'th.ratePh': 'اضغط على عدد النجوم ثم اكتب تعليقًا (اختياري)',
      'th.comment': 'تعليقك',
      'th.commentPh': 'اشرح تجربتك مع الأستاذ...',
      'th.noRatings': 'لا تقييمات بعد — كن أول من يقيّم',
      'th.avg': 'التقييم المتوسط',
      'th.ratings': 'تقييمات',
      'th.rating': 'تقييم',
      'th.confirmDel': 'حذف الأستاذ «{name}»؟',
      'th.confirmDelHint': 'ستُحذف صورته وتقييماته نهائيًا.',
      'th.empty': 'لا أساتذة بعد',
      'th.emptyHint': 'أضف أساتذة موادك ثم قيّمهم ليراها الجميع.',
      'th.todayRate': 'قيّم الآن',

      'ct.title': 'جهات الاتصال',
      'ct.add': 'إضافة جهة',
      'ct.edit': 'تعديل الجهة',
      'ct.name': 'اسم الجهة',
      'ct.namePh': 'مثال: الدكتور أحمد',
      'ct.category': 'الفئة',
      'ct.org': 'الجهة / المؤسسة (اختياري)',
      'ct.orgPh': 'مثال: كلية الهندسة',
      'ct.phone': 'رقم الهاتف',
      'ct.addPhone': 'إضافة رقم',
      'ct.email': 'البريد الإلكتروني',
      'ct.addEmail': 'إضافة بريد',
      'ct.photo': 'الصورة',
      'ct.note': 'ملاحظة (اختياري)',
      'ct.notePh': 'أي تفاصيل تهمك عن هذه الجهة...',
      'ct.empty': 'لا جهات بعد',
      'ct.emptyHint': 'أضف أرقام وإيميلات أساتذتك والجهات المهمة.',
      'ct.searchPh': 'ابحث بالاسم أو الرقم أو البريد...',
      'ct.call': 'اتصال',
      'ct.mail': 'مراسلة',
      'ct.confirmDel': 'حذف جهة «{name}»؟',
      'ct.confirmDelHint': 'لا يمكن التراجع عن الحذف.',
      'ct.catTeacher': 'أستاذ',
      'ct.catAdmin': 'إدارة',
      'ct.catDeanery': 'عمادة',
      'ct.catCenter': 'مركز',
      'ct.catOther': 'أخرى',
      'ct.catAll': 'الكل',
      'ct.count': '{n} من {total} جهة',
      'ct.noResults': 'لا نتائج مطابقة',

      't.needSubjects': 'لا توجد مواد بعد — أضف مواد فصلك الحالي لترميز المهام بالألوان.',

      'cal.prev': 'الشهر السابق',
      'cal.next': 'الشهر التالي',

      's.title': 'المواد',
      's.forSem': 'مواد {sem}',
      's.name': 'اسم المادة',
      's.namePh': 'مثال: رياضيات',
      's.color': 'اللون',
      's.deleteQ': 'حذف مادة «{name}»؟',
      's.deleteHint': 'ستصبح المهام والملاحظات المرتبطة بها «بدون مادة».',
      's.empty': 'لا مواد في هذا الفصل',
      's.emptyHint': 'أضف مواد فصلك لتأخذ المهام والملاحظات ألوانها.',
      's.goProfile': 'تعريف الفصل من الملف الشخصي',
      's.noCurrent': 'لم تُعرّف فصلك الحالي بعد.',
      's.teacher': 'الأستاذ',
      's.noTeacher': 'بدون أستاذ',

      'n.title': 'الملاحظات',
      'n.pin': 'تثبيت في الأعلى',
      'n.new': 'ملاحظة جديدة',
      'n.edit': 'تعديل الملاحظة',
      'n.noteTitle': 'العنوان (اختياري)',
      'n.titlePh': 'مثال: قوانين نيوتن',
      'n.text': 'النص',
      'n.textPh': 'اكتب ملاحظتك هنا…',
      'n.addImage': 'إضافة صورة',
      'n.images': 'الصور',
      'n.subject': 'المادة',
      'n.noSubject': 'بدون مادة',
      'n.deleteQ': 'حذف هذه الملاحظة؟',
      'n.empty': 'لا ملاحظات بعد',
      'n.emptyHint': 'دوّن أول ملاحظة، وألصق بها صورًا إن أحببت.',
      'n.searchPh': 'ابحث في الملاحظات…',
      'n.filterAll': 'الكل',
      'n.filterNone': 'بدون مادة',
      'n.noResults': 'لا نتائج مطابقة',
      'n.noResultsHint': 'جرّب كلمة أخرى أو أزل التصفية.',
      'n.imgFailed': 'تعذّر إضافة هذه الصورة',

      'p.title': 'ملفي',
      'p.student': 'بيانات الطالب',
      'p.degree': 'الدرجة العلمية',
      'p.degreePh': 'مثال: بكالوريوس',
      'p.specialty': 'التخصص',
      'p.specialtyPh': 'مثال: هندسة البرمجيات',
      'p.group': 'المجموعة',
      'p.groupPh': 'مثال: م-202',
      'p.position': 'وضعي الدراسي الحالي',
      'p.now': 'الآن: {year} · {sem}',
      'p.pickYear': 'السنة',
      'p.pickSem': 'الفصل',
      'p.structure': 'الهيكل الدراسي',
      'p.editStructure': 'تعديل الهيكل',
      'p.years': 'عدد السنوات',
      'p.semsPerYear': 'الفصول في كل سنة',
      'p.addYear': 'إضافة سنة',
      'p.delYearQ': 'حذف هذه السنة بكل فصولها؟',
      'p.delYearHint': 'ستُحذف مواد فصولها أيضًا.',
      'p.delSemQ': 'حذف هذا الفصل؟',
      'p.delSemHint': 'ستُحذف موادّه أيضًا.',
      'p.setup': 'لنضبط درجتك العلمية',
      'p.setupHint': 'حدد عدد سنوات الدرجة وعدد الفصول في كل سنة، ثم حدد موقعك الحالي.',
      'p.subjects': 'المواد حسب الفصل',
      'p.manageFor': 'إدارة مواد {sem}',
      'p.newSem': 'فصل جديد / تغيير المواد',
      'p.newSemHint': 'اختر فصلًا، أدخل موادّه، ثم عيّنه فصلًا حاليًا.',
      'p.pickSemester': 'اختر الفصل',
      'p.pickHint': 'الفصول حسب السنوات:',
      'p.markCurrent': 'تعيين كفصل حالي',
      'p.markDone': 'وضع علامة «منتهٍ»',
      'p.markFuture': 'إعادة إلى «قادم»',
      'p.subjectsCount': '{n} مادة',
      'p.data': 'بياناتي',
      'p.export': 'تصدير نسخة احتياطية',
      'p.import': 'استيراد نسخة',
      'p.reset': 'مسح جميع البيانات',
      'p.resetQ': 'مسح جميع البيانات نهائيًا؟',
      'p.resetHint': 'سيُحذف كل شيء: المهام والملاحظات والمواد والهيكل. لا تراجع بعدها.',
      'p.noStructure': 'عرّف هيكلك الدراسي أولًا.',
      'p.vault': 'قفل صفحة كلمات السر',
      'p.vaultChange': 'تغيير الرمز',
      'p.vaultHintLabel': 'أدخل التلميحة للمتابعة',
      'p.vaultHintPh': 'التلميحة التي كتبتها عند إنشاء القفل',
      'p.vaultContinue': 'متابعة',
      'p.vaultNewPin': 'الرمز الجديد (4 أرقام)',
      'p.vaultNewPinConfirm': 'تأكيد الرمز الجديد',
      'p.vaultSave': 'حفظ الرمز الجديد',
      'p.vaultHintWrong': 'التلميحة غير صحيحة',
      'p.vaultChanged': 'تم تغيير الرمز بنجاح',
      'p.vaultNotSet': 'القفل غير مُنشأ بعد — افتح صفحة «الحسابات» أول مرة لإنشائه.',
      'p.currentIs': 'فصلك الحالي',
      'p.prefs': 'التفضيلات',
      'p.weekStart': 'بداية الأسبوع',
      'ws.mon': 'الاثنين',
      'ws.sat': 'السبت',
      'ws.sun': 'الأحد',
      'p.about': 'عن التطبيق',
      'p.version': 'الإصدار {v}',
      'p.storage': 'التخزين المستخدم: {mb} م.ب',

      'year.name': 'السنة {w}',
      'year.w1': 'الأولى',
      'year.w2': 'الثانية',
      'year.w3': 'الثالثة',
      'year.w4': 'الرابعة',
      'year.w5': 'الخامسة',
      'year.w6': 'السادسة',
      'year.w7': 'السابعة',
      'year.w8': 'الثامنة',
      'sem.name': 'الفصل {n}',

      'st.current': 'الحالي',
      'st.done': 'منتهٍ',
      'st.future': 'قادم',

      'dl.bachelor': 'بكالوريوس',
      'dl.master': 'ماجستير',
      'dl.phd': 'دكتوراه',

      'toast.saved': 'تم الحفظ',
      'toast.deleted': 'تم الحذف',
      'toast.storageFull': 'الذاكرة ممتلئة — احذف بعض الصور من الملاحظات',
      'toast.importedN': 'تم الاستيراد: {t} مهمة و {n} ملاحظة',
      'toast.importBad': 'ملف غير صالح',
      'toast.langSet': 'تم تغيير اللغة',
      'toast.cloudSyncSuccess': 'تمت المزامنة مع السحابة ☁️',
      'toast.cloudSyncFail': 'تعذرت المزامنة — تحقق من الاتصال',
      'toast.cloudDisabled': 'المزامنة السحابية معطلة (لم يتم تكوين Supabase)',

      /* Cloud sync / auth */
      'cloud.title': 'المزامنة السحابية',
      'cloud.subtitle': 'سجّل دخولك بحساب جوجل لحفظ بياناتك في السحابة والوصول إليها من أي جهاز.',
      'cloud.signIn': 'تسجيل الدخول بحساب جوجل',
      'cloud.signInDesc': 'بياناتك المحلية ستُرفع تلقائياً عند أول تسجيل دخول وتُزامَن عند كل تغيير.',
      'cloud.signedIn': 'متصل بحساب',
      'cloud.signOut': 'تسجيل الخروج',
      'cloud.syncNow': 'مزامنة الآن',
      'cloud.syncing': 'جارٍ المزامنة…',
      'cloud.lastSync': 'آخر مزامنة: {time}',
      'cloud.neverSync': 'لم تتم المزامنة بعد',
      'cloud.connected': 'متصل ☁️',
      'cloud.offline': 'غير متصل',
      'cloud.dataSafe': 'بياناتك آمنة على هذا الجهاز حتى بدون اتصال.',
      'cloud.mergeNote': 'البيانات من السحابة و الجهاز المحلي تُدمج تلقائياً.',
      'cloud.deleteAccount': 'حذف الحساب',
      'cloud.signOutConfirm': 'هل تريد تسجيل الخروج؟ ستبقى بياناتك على هذا الجهاز لكن المزامنة ستتوقف.',
      'cloud.deleteAccountConfirm': 'هل أنت متأكد من حذف الحساب نهائياً؟ سيتم حذف جميع بياناتك السحابية والجلية. هذا الإجراء لا يمكن التراجع عنه.',
      'cloud.deleteAccountError': 'تعذّر حذف الحساب — حاول مجدداً',
      'cloud.loginTitle': 'سجّل دخولك للمتابعة',
      'cloud.loginHint': 'ادخل بحساب جوجل لمزامنة بياناتك وحفظها في السحابة.',
      'cloud.loginBtn': 'الدخول بحساب جوجل',
      'cloud.loginError': 'فشل تسجيل الدخول — حاول مرة أخرى',
      'auth.subtitle': 'سجّل دخولك لحفظ بياناتك ومزامنتها عبر أجهزتك',
      'auth.signIn': 'المتابعة بحساب جوجل',
      'auth.hint': 'بياناتك محفوظة بأمان في حسابك — لن تُفقد أبداً',
      'auth.fail': 'فشل تسجيل الدخول — حاول مرة أخرى',

      /* Motivational messages */
      'mo.great': 'أحسنت! أنت على المسار الصحيح 🎓',
      'mo.allDone': 'ممتاز! أنجزت كل مهام اليوم ✨',
      'mo.keepGoing': 'واصل — لم يتبقَّ إلا القليل 💪',
      'mo.start': 'ابدأ يومك بأول مهمة!',
      'mo.noTasks': 'استمتع بيومك — لا مهام اليوم 🌤️',
      'mo.statsHigh': 'أداؤك ممتاز — استمر بنفس القوة! 🏆',
      'mo.statsMid': 'أداء جيد — بضع خطوات ويكتمل! 📚',
      'mo.statsLow': 'لا بأس — كل خطوة تقرّبك أكثر! 🌱',

      /* Streaks */
      'str.label': 'أيام متتالية',
      'str.days': '{n} يوم',

      /* Places extra */
      'pl.lat': 'خط العرض',
      'pl.lng': 'خط الطول',
      'pl.noPlaces': 'لا توجد مواقع محفوظة بعد. أضف موقعك الأول!',
      'pl.latLngRequired': 'يرجى إدخال خط العرض وخط الطول',
      'pl.openExt': 'فتح في خرائط Yandex',
      'pl.count': '{n} موقع',
      'pl.filterPh': 'ابحث في مواقعك… (اسم، وصف، إحداثيات)',
      'pl.view': 'عرض على الخريطة',
      'pl.copyCoords': 'نسخ الإحداثيات',
      'pl.copied': 'تم نسخ الإحداثيات',
      'pl.searchLabel': 'تحديد الموقع',
      'pl.searchPh': 'ابحث عن عنوان أو الصق إحداثيات (24.71, 46.67)',
      'pl.noResults': 'لا نتائج',
      'pl.searching': 'جارٍ البحث…',
      'pl.searchFail': 'تعذّر البحث — تحقق من الاتصال',
      'pl.parsed': 'استخدام هذه الإحداثيات',
      'pl.mapOffline': 'تعذّر الوصول إلى خرائط Yandex — تم التحويل إلى OpenStreetMap',
  'pl.mapError': 'تعذّر تحميل خرائط الشبكة — تحقق من اتصالك أو عطّل مانع الإعلانات لهذا الموقع ثم أعد المحاولة',
  'pl.retry': 'إعادة المحاولة',
    },


    ru: {
      'app.tagline': 'Ваш цифровой студенческий ежедневник — задачи, заметки и семестры',

      'nav.overview': 'Обзор',
      'nav.tasks': 'Задачи',
      'nav.notes': 'Заметки',
      'nav.stats': 'Статистика',
      'nav.vault': 'Пароли',
      'nav.teachers': 'Преподаватели',
      'nav.contacts': 'Контакты',
      'nav.profile': 'Профиль',

      'v.title': 'Пароли и аккаунты',
      'v.setupTitle': 'Создать замок страницы',
      'v.setupHint': 'Придумайте код из 4 цифр и напишите подсказку — только подсказка позволит сменить код позже в «Профиле».',
      'v.pin': 'Код (4 цифры)',
      'v.pinConfirm': 'Подтвердите код',
      'v.hint': 'Подсказка',
      'v.hintPh': 'Фраза, слово или цифры — знаете только вы',
      'v.create': 'Создать замок',
      'v.pinMismatch': 'Коды не совпадают',
      'v.need4': 'Введите 4 цифры',
      'v.unlockTitle': 'Страница заблокирована',
      'v.unlockSub': 'Введите код из 4 цифр, чтобы увидеть аккаунты',
      'v.unlock': 'Открыть',
      'v.wrongPin': 'Неверный код — попробуйте снова',
      'v.lockedOut': 'Слишком много попыток — подождите {time} и попробуйте снова',
      'v.lockBtn': 'Заблокировать',
      'v.add': 'Добавить аккаунт',
      'v.editTitle': 'Изменить аккаунт',
      'v.entryTitle': 'Название',
      'v.entryTitlePh': 'Например: аккаунт университета',
      'v.username': 'Имя аккаунта (необязательно)',
      'v.usernamePh': 'Например: yousef.m2026',
      'v.url': 'Ссылка на сайт/программу (необязательно)',
      'v.urlPh': 'https://…',
      'v.password': 'Пароль',
      'v.desc': 'Описание пароля (необязательно)',
      'v.descPh': 'Например: как код телефона',
      'v.empty': 'Пока нет сохранённых аккаунтов',
      'v.emptyHint': 'Добавьте первый аккаунт — он будет скрыт за вашим кодом.',
      'v.deleteQ': 'Удалить аккаунт «{name}»?',
      'v.deleteHint': 'Пароль нельзя будет вернуть.',
      'v.copied': 'Пароль скопирован',
      'v.copyFail': 'Не удалось скопировать — скопируйте вручную',
      'v.security': 'Защищено вашим кодом на этом устройстве — данные не покидают браузер.',
      'v.searchPh': 'Поиск по аккаунтам…',
      'nav.tasks': 'Задачи',
      'nav.notes': 'Заметки',
      'nav.stats': 'Статистика',
      'nav.profile': 'Профиль',

      'sh.ratio': 'Доля выполнения',
      'sh.done': 'Выполнено',
      'sh.notDone': 'Не выполнено',
      'sh.busiestDays': 'Самые загруженные дни',
      'sh.topSubjects': 'Предметы с большинством задач',
      'sh.mostMissed': 'Предметы с пропусками',
      'sh.standing': 'Моё положение по предметам',
      'sh.standingHint': 'Двигайте ползунок: красный — трудно мне, зелёный — уверен. Каждое изменение сохраняется с датой.',
      'sh.hard': 'Трудно мне',
      'sh.good': 'Уверенно',
      'sh.hardest': 'Самые трудные предметы',
      'sh.noStanding': 'Пока нет записей — подвиньте ползунки выше.',
      'sh.improved': 'Улучшилось',
      'sh.declined': 'Ухудшилось',
      'sh.unchanged': 'Пока без изменений',
      'sh.lastChanged': 'Обновлено: {date}',
      'sh.noTasks': 'Задач пока нет — статистике нечего показать',
      'sh.noTasksHint': 'Добавьте задачи, и цифры появятся здесь автоматически.',
      'sh.noSubjects': 'Сначала добавьте предметы на странице задач или в профиле.',
      'sh.ofTotal': 'из {n}',
      'sh.summary': 'Выполнено {done} из {total} задач',

      'ov.gMorning': 'Доброе утро',
      'ov.gAfternoon': 'Хорошего дня',
      'ov.gEvening': 'Добрый вечер',
      'ov.statsToday': 'Задачи на сегодня',
      'ov.statsDone': 'Выполнено сегодня',
      'ov.statsBacklog': 'Просроченные',
      'ov.statsNotes': 'Заметки',
      'ov.week': 'На этой неделе',
      'ov.weekEmpty': 'В ближайшие 7 дней задач нет',

      'a.save': 'Сохранить',
      'a.cancel': 'Отмена',
      'a.delete': 'Удалить',
      'a.edit': 'Изменить',
      'a.add': 'Добавить',
      'a.close': 'Закрыть',
      'a.done': 'Готово',
      'a.today': 'Сегодня',
      'a.none': 'Нет',
      'a.all': 'Все',
      'a.search': 'Поиск',
      'a.create': 'Создать',

      'hdr.lang': 'Язык',
      'hdr.theme': 'Тема',

      'ob.welcome': 'Добро пожаловать в Study Live',
      'ob.tag': 'Наведите порядок: задачи по дням, заметки по предметам, ваши семестры.',
      'ob.lang': 'Выберите язык',
      'ob.theme': 'Оформление',
      'ob.light': 'Светлое',
      'ob.dark': 'Тёмное',
      'ob.start': 'Начать',

      't.title': 'Задачи',
      't.add': 'Новая задача',
      't.modeDay': 'Задачи дня',
      't.modeAll': 'Все задачи',
      't.groupBacklog': 'Просроченные',
      't.groupUpcoming': 'Предстоящие',
      't.groupDone': 'Выполненные',
      't.backlogEmpty': 'Просроченного нет — всё под контролем',
      't.upcomingEmpty': 'Предстоящих задач нет',
      't.doneEmpty': 'Пока ничего не выполнено',
      't.emptyAll': 'Задач пока нет',
      't.emptyAllHint': 'Нажмите «+», чтобы добавить первую задачу — можно выбрать любой день, даже прошедший.',
      't.edit': 'Изменить задачу',
      't.taskTitle': 'Название задачи',
      't.taskTitlePh': 'Например: повторить лекцию по статистике',
      't.desc': 'Описание (необязательно)',
      't.descPh': 'Детали: страницы, источники, заметки…',
      't.date': 'День',
      't.difficulty': 'Сложность',
      't.diffHard': 'Сложная',
      't.diffEasy': 'Лёгкая',
      't.diffLight': 'Простая',
      't.subject': 'Предмет',
      't.noSubject': 'Без предмета',
      't.subjectsBtn': 'Предметы',
      't.markAllDone': 'Выполнить все',
      't.enableProgress': 'Включить прогресс',
      't.progress': 'Прогресс',
      't.emptyDay': 'На этот день задач нет',
      't.emptyDayHint': 'Нажмите «+», чтобы добавить первую задачу.',
      't.count': 'задач: {n}',
      't.agNoTasks': 'нет задач',
      't.overdue': 'Просрочено',
      't.deleteQ': 'Удалить эту задачу?',
      't.confirmDel': 'Удалить эту задачу?',
      't.needSubjects': 'Предметов пока нет — добавьте предметы текущего семестра, чтобы задачи получали цвет.',

      'nav.places': 'Места',
      'pl.add': 'Добавить новое место',
      'pl.editTitle': 'Изменить место',
      'pl.name': 'Название места',
      'pl.namePh': 'Например: главная библиотека университета',
      'pl.desc': 'Описание (необязательно)',
      'pl.descPh': 'Заметки об этом месте...',
      'pl.color': 'Цвет маркера',
      'pl.nameRequired': 'Пожалуйста, введите название места',
      'pl.search': 'Найти место...',
      'pl.searchBtn': 'Поиск',
      'pl.useGps': 'Использовать моё местоположение',
      'pl.gpsError': 'Не удалось определить местоположение',
  'pl.gpsDenied': 'Доступ к местоположению запрещён — нажмите значок замка/ⓘ у адресной строки, разрешите доступ и повторите',
  'pl.gpsUnavailable': 'Устройство не может определить местоположение — включите службу определения местоположения в Windows',
  'pl.gpsTimeout': 'Время определения местоположения истекло — проверьте интернет и попробуйте снова',
  'pl.gpsUnsupported': 'Ваш браузер не поддерживает геолокацию',
  'pl.gpsDone': 'Координаты заполнены по вашему текущему местоположению',
  'pl.locate': 'Показать моё местоположение на карте',
  'pl.locating': 'Определяем ваше местоположение…',
  'pl.located': 'Вы здесь',
      'pl.deleteQ': 'Удалить «{name}» навсегда?',

      'th.title': 'Преподаватели и оценки',
      'th.add': 'Добавить преподавателя',
      'th.edit': 'Изменить преподавателя',
      'th.name': 'Имя преподавателя',
      'th.namePh': 'Например: пр. Ахмед аль-Али',
      'th.subject': 'Предмет',
      'th.noSubject': 'Без предмета',
      'th.subjectPh': 'Предмет, который он ведёт',
      'th.photo': 'Фото преподавателя',
      'th.addPhoto': 'Добавить фото',
      'th.changePhoto': 'Сменить фото',
      'th.removePhoto': 'Убрать фото',
      'th.rate': 'Оценить',
      'th.rateTitle': 'Оценить преподавателя',
      'th.ratePh': 'Выберите звёзды и напишите отзыв (необязательно)',
      'th.comment': 'Ваш отзыв',
      'th.commentPh': 'Расскажите о занятиях...',
      'th.noRatings': 'Оценок пока нет — станьте первым',
      'th.avg': 'Средняя оценка',
      'th.ratings': 'Оценки',
      'th.rating': 'Оценка',
      'th.confirmDel': 'Удалить преподавателя «{name}»?',
      'th.confirmDelHint': 'Фото и оценки будут удалены навсегда.',
      'th.empty': 'Преподавателей пока нет',
      'th.emptyHint': 'Добавьте преподавателей и оцените их.',
      'th.todayRate': 'Оценить сейчас',

      'ct.title': 'Контакты',
      'ct.add': 'Добавить контакт',
      'ct.edit': 'Изменить контакт',
      'ct.name': 'Имя контакта',
      'ct.namePh': 'Например: доктор Ахмед',
      'ct.category': 'Категория',
      'ct.org': 'Организация (необязательно)',
      'ct.orgPh': 'Например: инженерный факультет',
      'ct.phone': 'Телефон',
      'ct.addPhone': 'Добавить номер',
      'ct.email': 'Эл. почта',
      'ct.addEmail': 'Добавить почту',
      'ct.photo': 'Фото',
      'ct.note': 'Заметка (необязательно)',
      'ct.notePh': 'Любые детали о контакте...',
      'ct.empty': 'Контактов пока нет',
      'ct.emptyHint': 'Добавьте телефоны и почту преподавателей и важных людей.',
      'ct.searchPh': 'Поиск по имени, номеру или почте...',
      'ct.call': 'Позвонить',
      'ct.mail': 'Написать',
      'ct.confirmDel': 'Удалить контакт «{name}»?',
      'ct.confirmDelHint': 'Действие необратимо.',
      'ct.catTeacher': 'Преподаватель',
      'ct.catAdmin': 'Администрация',
      'ct.catDeanery': 'Деканат',
      'ct.catCenter': 'Центр',
      'ct.catOther': 'Другое',
      'ct.catAll': 'Все',
      'ct.count': '{n} из {total}',
      'ct.noResults': 'Нет совпадений',

      'cal.prev': 'Прошлый месяц',
      'cal.next': 'Следующий месяц',

      's.title': 'Предметы',
      's.forSem': 'Предметы — {sem}',
      's.name': 'Название предмета',
      's.namePh': 'Например: Математика',
      's.color': 'Цвет',
      's.deleteQ': 'Удалить предмет «{name}»?',
      's.deleteHint': 'Связанные задачи и заметки станут «Без предмета».',
      's.empty': 'В этом семестре предметов нет',
      's.emptyHint': 'Добавьте предметы — задачи и заметки возьмут их цвета.',
      's.goProfile': 'Настроить семестр в профиле',
      's.noCurrent': 'Текущий семестр ещё не выбран.',
      's.teacher': 'Преподаватель',
      's.noTeacher': 'Без преподавателя',

      'n.title': 'Заметки',
      'n.pin': 'Закрепить вверху',
      'n.new': 'Новая заметка',
      'n.edit': 'Изменить заметку',
      'n.noteTitle': 'Заголовок (необязательно)',
      'n.titlePh': 'Например: законы Ньютона',
      'n.text': 'Текст',
      'n.textPh': 'Напишите заметку здесь…',
      'n.addImage': 'Добавить фото',
      'n.images': 'Фото',
      'n.subject': 'Предмет',
      'n.noSubject': 'Без предмета',
      'n.deleteQ': 'Удалить эту заметку?',
      'n.empty': 'Заметок пока нет',
      'n.emptyHint': 'Запишите первую заметку — можно с фото.',
      'n.searchPh': 'Поиск по заметкам…',
      'n.filterAll': 'Все',
      'n.filterNone': 'Без предмета',
      'n.noResults': 'Ничего не найдено',
      'n.noResultsHint': 'Попробуйте другое слово или снимите фильтр.',
      'n.imgFailed': 'Не удалось добавить это фото',

      'p.title': 'Профиль',
      'p.student': 'Данные студента',
      'p.degree': 'Степень',
      'p.degreePh': 'Например: Бакалавриат',
      'p.specialty': 'Специальность',
      'p.specialtyPh': 'Например: Программная инженерия',
      'p.group': 'Группа',
      'p.groupPh': 'Например: М-202',
      'p.position': 'Текущее положение',
      'p.now': 'Сейчас: {year} · {sem}',
      'p.pickYear': 'Курс',
      'p.pickSem': 'Семестр',
      'p.structure': 'Структура обучения',
      'p.editStructure': 'Изменить структуру',
      'p.years': 'Курсов',
      'p.semsPerYear': 'Семестров в году',
      'p.addYear': 'Добавить курс',
      'p.delYearQ': 'Удалить этот курс со всеми семестрами?',
      'p.delYearHint': 'Предметы его семестров тоже будут удалены.',
      'p.delSemQ': 'Удалить этот семестр?',
      'p.delSemHint': 'Его предметы тоже будут удалены.',
      'p.setup': 'Настроим вашу программу',
      'p.setupHint': 'Укажите количество курсов и семестров в каждом курсе, затем отметьте текущее положение.',
      'p.subjects': 'Предметы по семестрам',
      'p.manageFor': 'Предметы — {sem}',
      'p.newSem': 'Новый семестр / сменить предметы',
      'p.newSemHint': 'Выберите семестр, добавьте его предметы и назначьте его текущим.',
      'p.pickSemester': 'Выберите семестр',
      'p.pickHint': 'Семестры по курсам:',
      'p.markCurrent': 'Сделать текущим',
      'p.markDone': 'Отметить «завершён»',
      'p.markFuture': 'Вернуть в «будущие»',
      'p.subjectsCount': 'предметов: {n}',
      'p.data': 'Мои данные',
      'p.export': 'Экспорт резервной копии',
      'p.import': 'Импорт копии',
      'p.reset': 'Стереть все данные',
      'p.resetQ': 'Стереть все данные безвозвратно?',
      'p.resetHint': 'Будут удалены задачи, заметки, предметы и структура. Это необратимо.',
      'p.noStructure': 'Сначала задайте структуру обучения.',
      'p.vault': 'Замок страницы паролей',
      'p.vaultChange': 'Сменить код',
      'p.vaultHintLabel': 'Введите подсказку, чтобы продолжить',
      'p.vaultHintPh': 'Подсказка, которую вы wrote при создании',
      'p.vaultContinue': 'Продолжить',
      'p.vaultNewPin': 'Новый код (4 цифры)',
      'p.vaultNewPinConfirm': 'Подтвердите новый код',
      'p.vaultSave': 'Сохранить новый код',
      'p.vaultHintWrong': 'Неверная подсказка',
      'p.vaultChanged': 'Код успешно изменён',
      'p.vaultNotSet': 'Замок ещё не создан — откройте страницу «Пароли», чтобы создать его.',
      'p.currentIs': 'Текущий семестр',
      'p.prefs': 'Настройки',
      'p.weekStart': 'Начало недели',
      'ws.mon': 'Понедельник',
      'ws.sat': 'Суббота',
      'ws.sun': 'Воскресенье',
      'p.about': 'О приложении',
      'p.version': 'Версия {v}',
      'p.storage': 'Занято: {mb} МБ',

      'year.name': '{w} курс',
      'year.w1': '1-й',
      'year.w2': '2-й',
      'year.w3': '3-й',
      'year.w4': '4-й',
      'year.w5': '5-й',
      'year.w6': '6-й',
      'year.w7': '7-й',
      'year.w8': '8-й',
      'sem.name': '{n}-й семестр',

      'st.current': 'Текущий',
      'st.done': 'Завершён',
      'st.future': 'Будущий',

      'dl.bachelor': 'Бакалавриат',
      'dl.master': 'Магистратура',
      'dl.phd': 'Аспирантура',

      'toast.saved': 'Сохранено',
      'toast.deleted': 'Удалено',
      'toast.storageFull': 'Хранилище заполнено — удалите часть фото из заметок',
      'toast.importedN': 'Импортировано: {t} задач и {n} заметок',
      'toast.importBad': 'Неверный файл',
      'toast.langSet': 'Язык изменён',
      'toast.cloudSyncSuccess': 'Синхронизация с облаком завершена ☁️',
      'toast.cloudSyncFail': 'Ошибка синхронизации — проверьте подключение',
      'toast.cloudDisabled': 'Облачная синхронизация отключена (Supabase не настроен)',

      /* Cloud sync / auth */
      'cloud.title': 'Облачная синхронизация',
      'cloud.subtitle': 'Войдите через Google, чтобы сохранить данные в облако и получить доступ к ним с любого устройства.',
      'cloud.signIn': 'Войти через Google',
      'cloud.signInDesc': 'Ваши локальные данные автоматически загрузятся при первом входе и будут синхронизироваться при каждом изменении.',
      'cloud.signedIn': 'Вошли как',
      'cloud.signOut': 'Выйти',
      'cloud.syncNow': 'Синхронизировать',
      'cloud.syncing': 'Синхронизация…',
      'cloud.lastSync': 'Последняя синхронизация: {time}',
      'cloud.neverSync': 'Синхронизация ещё не выполнялась',
      'cloud.connected': 'В облаке ☁️',
      'cloud.offline': 'Не подключено',
      'cloud.dataSafe': 'Ваши данные в безопасности на этом устройстве даже без подключения.',
      'cloud.mergeNote': 'Данные из облака и локальные данные объединяются автоматически.',
      'cloud.deleteAccount': 'Удалить аккаунт',
      'cloud.signOutConfirm': 'Выйти из аккаунта? Ваши данные останутся на этом устройстве, но синхронизация прекратится.',
      'cloud.deleteAccountConfirm': 'Удалить аккаунт навсегда? Все данные будут удалены. Это действие нельзя отменить.',
      'cloud.deleteAccountError': 'Не удалось удалить аккаунт',
      'cloud.loginTitle': 'Войдите, чтобы продолжить',
      'cloud.loginHint': 'Войдите через Google, чтобы синхронизировать данные.',
      'cloud.loginBtn': 'Войти через Google',
      'cloud.loginError': 'Ошибка входа — попробуйте снова',
      'auth.subtitle': 'Войдите, чтобы сохранить данные и синхронизировать их между устройствами',
      'auth.signIn': 'Продолжить через Google',
      'auth.hint': 'Ваши данные надёжно хранятся в вашем аккаунте — они не потеряются',
      'auth.fail': 'Ошибка входа — попробуйте снова',

      /* Motivational messages */
      'mo.great': 'Отлично! Вы на правильном пути 🎓',
      'mo.allDone': 'Супер! Все задачи на сегодня выполнены ✨',
      'mo.keepGoing': 'Продолжайте — осталось совсем немного 💪',
      'mo.start': 'Начните день с первой задачи!',
      'mo.noTasks': 'Наслаждайтесь днем — сегодня нет задач 🌤️',
      'mo.statsHigh': 'Отличный результат — так держать! 🏆',
      'mo.statsMid': 'Хорошая работа — еще пара шагов! 📚',
      'mo.statsLow': 'Ничего страшного — каждый шаг приближает к цели! 🌱',

      /* Streaks */
      'str.label': 'Дней подряд',
      'str.days': '{n} дн.',

      /* Places extra */
      'pl.lat': 'Широта',
      'pl.lng': 'Долгота',
      'pl.noPlaces': 'Пока нет сохраненных мест. Добавьте первое!',
      'pl.latLngRequired': 'Укажите широту и долготу',
      'pl.openExt': 'Открыть в Яндекс Картах',
      'pl.count': '{n} мест',
      'pl.filterPh': 'Поиск по местам… (название, описание, координаты)',
      'pl.view': 'Показать на карте',
      'pl.copyCoords': 'Скопировать координаты',
      'pl.copied': 'Координаты скопированы',
      'pl.searchLabel': 'Определение места',
      'pl.searchPh': 'Найдите адрес или вставьте координаты (55.75, 37.61)',
      'pl.noResults': 'Нет результатов',
      'pl.searching': 'Поиск…',
      'pl.searchFail': 'Не удалось выполнить поиск — проверьте соединение',
      'pl.parsed': 'Использовать эти координаты',
      'pl.mapOffline': 'Карты Яндекс недоступны — переключено на OpenStreetMap',
  'pl.mapError': 'Не удалось загрузить карту — проверьте соединение или отключите блокировщик для этого сайта и повторите',
  'pl.retry': 'Повторить',
    },

    en: {
      'app.tagline': 'Your digital study planner — tasks, notes and semesters in one place',

      'nav.overview': 'Home',
      'nav.tasks': 'Tasks',
      'nav.notes': 'Notes',
      'nav.stats': 'Statistics',
      'nav.vault': 'Vault',
      'nav.profile': 'Profile',

      'v.title': 'Passwords & accounts',
      'v.setupTitle': 'Create the page lock',
      'v.setupHint': 'Pick a 4-digit code and write a hint — only the hint lets you change the code later from “Profile”.',
      'v.pin': 'Code (4 digits)',
      'v.pinConfirm': 'Confirm code',
      'v.hint': 'Hint',
      'v.hintPh': 'A phrase, word or numbers — only you know it',
      'v.create': 'Create lock',
      'v.pinMismatch': 'The two codes do not match',
      'v.need4': 'Enter 4 digits',
      'v.unlockTitle': 'Page locked',
      'v.unlockSub': 'Enter the 4-digit code to see your accounts',
      'v.unlock': 'Unlock',
      'v.wrongPin': 'Wrong code — try again',
      'v.lockedOut': 'Too many attempts — wait {time} and try again',
      'v.lockBtn': 'Lock page',
      'v.add': 'Add account',
      'v.editTitle': 'Edit account',
      'v.entryTitle': 'Title',
      'v.entryTitlePh': 'e.g. University account',
      'v.username': 'Account name (optional)',
      'v.usernamePh': 'e.g. yousef.m2026',
      'v.url': 'Site/app link (optional)',
      'v.urlPh': 'https://…',
      'v.password': 'Password',
      'v.desc': 'Password note (optional)',
      'v.descPh': 'e.g. same as my phone code',
      'v.empty': 'No saved accounts yet',
      'v.emptyHint': 'Add your first account — it stays hidden behind your code.',
      'v.deleteQ': 'Delete account “{name}”?',
      'v.deleteHint': 'The password cannot be recovered.',
      'v.copied': 'Password copied',
      'v.copyFail': 'Could not copy — reveal it and copy manually',
      'v.security': 'Protected by your code on this device — data never leaves your browser.',
      'v.searchPh': 'Search accounts…',
      'nav.tasks': 'Tasks',
      'nav.notes': 'Notes',
      'nav.stats': 'Statistics',
      'nav.profile': 'Profile',

      'sh.ratio': 'Completion rate',
      'sh.done': 'Completed',
      'sh.notDone': 'Uncompleted',
      'sh.busiestDays': 'Busiest days',
      'sh.topSubjects': 'Subjects with most tasks',
      'sh.mostMissed': 'Most missed subjects',
      'sh.standing': 'My standing per subject',
      'sh.standingHint': 'Slide for each subject: red = hard for me, green = confident. Every change is logged with its date.',
      'sh.hard': 'Hard for me',
      'sh.good': 'Confident',
      'sh.hardest': 'My hardest subjects',
      'sh.noStanding': 'No readings yet — move the sliders above.',
      'sh.improved': 'Improved',
      'sh.declined': 'Declined',
      'sh.unchanged': 'No change yet',
      'sh.lastChanged': 'Updated: {date}',
      'sh.noTasks': 'No tasks yet — nothing to chart',
      'sh.noTasksHint': 'Add your tasks and the numbers will appear here automatically.',
      'sh.noSubjects': 'Add subjects first from the Tasks page or your Profile.',
      'sh.ofTotal': 'of {n}',
      'sh.summary': '{done} of {total} tasks completed',

      'ov.gMorning': 'Good morning',
      'ov.gAfternoon': 'Good afternoon',
      'ov.gEvening': 'Good evening',
      'ov.statsToday': 'Tasks today',
      'ov.statsDone': 'Done today',
      'ov.statsBacklog': 'Overdue',
      'ov.statsNotes': 'Notes',
      'ov.week': 'This week',
      'ov.weekEmpty': 'No tasks in the next 7 days',

      'a.save': 'Save',
      'a.cancel': 'Cancel',
      'a.delete': 'Delete',
      'a.edit': 'Edit',
      'a.add': 'Add',
      'a.close': 'Close',
      'a.done': 'Done',
      'a.today': 'Today',
      'a.none': 'None',
      'a.all': 'All',
      'a.search': 'Search',
      'a.create': 'Create',

      'hdr.lang': 'Language',
      'hdr.theme': 'Theme',

      'ob.welcome': 'Welcome to Study Live',
      'ob.tag': 'Organize your studies: tasks by day, notes by subject, your semesters.',
      'ob.lang': 'Choose language',
      'ob.theme': 'Appearance',
      'ob.light': 'Light',
      'ob.dark': 'Dark',
      'ob.start': "Let's start",

      't.title': 'Tasks',
      't.add': 'New task',
      't.modeDay': 'Today',
      't.modeAll': 'All tasks',
      't.groupBacklog': 'Overdue',
      't.groupUpcoming': 'Upcoming',
      't.groupDone': 'Completed',
      't.backlogEmpty': 'Nothing overdue — you are on track',
      't.upcomingEmpty': 'No upcoming tasks',
      't.doneEmpty': 'Nothing completed yet',
      't.emptyAll': 'No tasks yet',
      't.emptyAllHint': 'Tap + to add your first task — any day works, even past ones.',
      't.edit': 'Edit task',
      't.taskTitle': 'Task title',
      't.taskTitlePh': 'e.g. Review the statistics lecture',
      't.desc': 'Description (optional)',
      't.descPh': 'Extra details: pages, references, notes…',
      't.date': 'Day',
      't.difficulty': 'Difficulty',
      't.diffHard': 'Hard',
      't.diffEasy': 'Easy',
      't.diffLight': 'Light',
      't.subject': 'Subject',
      't.noSubject': 'No subject',
      't.subjectsBtn': 'Subjects',
      't.markAllDone': 'Complete all',
      't.enableProgress': 'Enable progress',
      't.progress': 'Progress',
      't.emptyDay': 'No tasks on this day',
      't.emptyDayHint': 'Tap + to add your first task.',
      't.count': '{n} tasks',
      't.agNoTasks': 'no tasks',
      't.overdue': 'Overdue',
      't.deleteQ': 'Delete this task?',
      't.confirmDel': 'Delete this task?',
      't.needSubjects': 'No subjects yet — add subjects for your current semester to color tasks.',

      'nav.places': 'Places',
      'nav.teachers': 'Teachers',
      'nav.contacts': 'Contacts',
      'pl.add': 'Add a new place',
      'pl.editTitle': 'Edit place',
      'pl.name': 'Place name',
      'pl.namePh': 'e.g. Main university library',
      'pl.desc': 'Description (optional)',
      'pl.descPh': 'Notes about this place...',
      'pl.color': 'Marker color',
      'pl.nameRequired': 'Please enter the place name',
      'pl.search': 'Search for a place...',
      'pl.searchBtn': 'Search',
      'pl.useGps': 'Use my current location',
      'pl.gpsError': 'Could not determine location',
  'pl.gpsDenied': 'Location permission denied — click the lock/ⓘ icon next to the address bar, allow location, then retry',
  'pl.gpsUnavailable': 'The device cannot determine your location — enable the Location service in Windows settings',
  'pl.gpsTimeout': 'Location request timed out — check your internet connection and try again',
  'pl.gpsUnsupported': 'Your browser does not support geolocation',
  'pl.gpsDone': 'Coordinates filled from your current location',
  'pl.locate': 'Show my location on the map',
  'pl.locating': 'Locating you…',
  'pl.located': 'You are here',
      'pl.deleteQ': 'Delete "{name}" permanently?',

      'th.title': 'Teachers & reviews',
      'th.add': 'Add teacher',
      'th.edit': 'Edit teacher',
      'th.name': 'Teacher name',
      'th.namePh': 'e.g. Prof. Ahmed Al-Ali',
      'th.subject': 'Subject',
      'th.noSubject': 'No subject',
      'th.subjectPh': 'The subject they teach',
      'th.photo': 'Teacher photo',
      'th.addPhoto': 'Add photo',
      'th.changePhoto': 'Change photo',
      'th.removePhoto': 'Remove photo',
      'th.rate': 'Rate',
      'th.rateTitle': 'Rate this teacher',
      'th.ratePh': 'Tap the stars, then leave a comment (optional)',
      'th.comment': 'Your comment',
      'th.commentPh': 'Tell others about your experience...',
      'th.noRatings': 'No reviews yet — be the first to rate',
      'th.avg': 'Average rating',
      'th.ratings': 'Reviews',
      'th.rating': 'Rating',
      'th.confirmDel': 'Delete teacher “{name}”?',
      'th.confirmDelHint': 'Their photo and reviews will be deleted forever.',
      'th.empty': 'No teachers yet',
      'th.emptyHint': 'Add your teachers, then rate them for everyone to see.',
      'th.todayRate': 'Rate now',

      'ct.title': 'Contacts',
      'ct.add': 'Add contact',
      'ct.edit': 'Edit contact',
      'ct.name': 'Contact name',
      'ct.namePh': 'e.g. Dr. Ahmed',
      'ct.category': 'Category',
      'ct.org': 'Organization (optional)',
      'ct.orgPh': 'e.g. Faculty of Engineering',
      'ct.phone': 'Phone',
      'ct.addPhone': 'Add number',
      'ct.email': 'Email',
      'ct.addEmail': 'Add email',
      'ct.photo': 'Photo',
      'ct.note': 'Note (optional)',
      'ct.notePh': 'Any details about this contact...',
      'ct.empty': 'No contacts yet',
      'ct.emptyHint': 'Add phones and emails of your teachers and key people.',
      'ct.searchPh': 'Search by name, number or email...',
      'ct.call': 'Call',
      'ct.mail': 'Email',
      'ct.confirmDel': 'Delete contact “{name}”?',
      'ct.confirmDelHint': 'This cannot be undone.',
      'ct.catTeacher': 'Teacher',
      'ct.catAdmin': 'Admin',
      'ct.catDeanery': 'Deanery',
      'ct.catCenter': 'Center',
      'ct.catOther': 'Other',
      'ct.catAll': 'All',
      'ct.count': '{n} of {total}',
      'ct.noResults': 'No matching results',

      'cal.prev': 'Previous month',
      'cal.next': 'Next month',

      's.title': 'Subjects',
      's.forSem': 'Subjects — {sem}',
      's.name': 'Subject name',
      's.namePh': 'e.g. Mathematics',
      's.color': 'Color',
      's.deleteQ': 'Delete subject “{name}”?',
      's.deleteHint': 'Its tasks and notes will become “No subject”.',
      's.empty': 'No subjects in this semester',
      's.emptyHint': 'Add subjects so tasks and notes take their colors.',
      's.goProfile': 'Set up the semester in Profile',
      's.noCurrent': 'Your current semester is not set yet.',
      's.teacher': 'Teacher',
      's.noTeacher': 'No teacher',

      'n.title': 'Notes',
      'n.pin': 'Pin to top',
      'n.new': 'New note',
      'n.edit': 'Edit note',
      'n.noteTitle': 'Title (optional)',
      'n.titlePh': 'e.g. Newton’s laws',
      'n.text': 'Text',
      'n.textPh': 'Write your note here…',
      'n.addImage': 'Add image',
      'n.images': 'Images',
      'n.subject': 'Subject',
      'n.noSubject': 'No subject',
      'n.deleteQ': 'Delete this note?',
      'n.empty': 'No notes yet',
      'n.emptyHint': 'Write your first note — attach images if you like.',
      'n.searchPh': 'Search notes…',
      'n.filterAll': 'All',
      'n.filterNone': 'No subject',
      'n.noResults': 'No matching results',
      'n.noResultsHint': 'Try another word or clear the filter.',
      'n.imgFailed': 'Could not add this image',

      'p.title': 'Profile',
      'p.student': 'Student details',
      'p.degree': 'Degree',
      'p.degreePh': 'e.g. Bachelor',
      'p.specialty': 'Major',
      'p.specialtyPh': 'e.g. Software Engineering',
      'p.group': 'Group',
      'p.groupPh': 'e.g. M-202',
      'p.position': 'Current position',
      'p.now': 'Now: {year} · {sem}',
      'p.pickYear': 'Year',
      'p.pickSem': 'Semester',
      'p.structure': 'Academic structure',
      'p.editStructure': 'Edit structure',
      'p.years': 'Years',
      'p.semsPerYear': 'Semesters per year',
      'p.addYear': 'Add year',
      'p.delYearQ': 'Delete this year with all its semesters?',
      'p.delYearHint': 'Their subjects will be deleted too.',
      'p.delSemQ': 'Delete this semester?',
      'p.delSemHint': 'Its subjects will be deleted too.',
      'p.setup': "Let's set up your degree",
      'p.setupHint': 'Set the number of years and semesters per year, then mark where you are now.',
      'p.subjects': 'Subjects by semester',
      'p.manageFor': 'Manage subjects — {sem}',
      'p.newSem': 'New semester / change subjects',
      'p.newSemHint': 'Pick a semester, add its subjects, then set it as current.',
      'p.pickSemester': 'Pick a semester',
      'p.pickHint': 'Semesters by year:',
      'p.markCurrent': 'Set as current semester',
      'p.markDone': 'Mark as finished',
      'p.markFuture': 'Move back to upcoming',
      'p.subjectsCount': '{n} subjects',
      'p.data': 'My data',
      'p.export': 'Export backup',
      'p.import': 'Import backup',
      'p.reset': 'Erase all data',
      'p.resetQ': 'Erase all data permanently?',
      'p.resetHint': 'Everything will be deleted: tasks, notes, subjects and structure. This cannot be undone.',
      'p.noStructure': 'Set up your academic structure first.',
      'p.vault': 'Passwords page lock',
      'p.vaultChange': 'Change code',
      'p.vaultHintLabel': 'Enter the hint to continue',
      'p.vaultHintPh': 'The hint you wrote when creating the lock',
      'p.vaultContinue': 'Continue',
      'p.vaultNewPin': 'New code (4 digits)',
      'p.vaultNewPinConfirm': 'Confirm new code',
      'p.vaultSave': 'Save new code',
      'p.vaultHintWrong': 'Wrong hint',
      'p.vaultChanged': 'Code changed successfully',
      'p.vaultNotSet': 'The lock is not created yet — open the “Vault” page first to create it.',
      'p.currentIs': 'Your current semester',
      'p.prefs': 'Preferences',
      'p.weekStart': 'Week starts on',
      'ws.mon': 'Monday',
      'ws.sat': 'Saturday',
      'ws.sun': 'Sunday',
      'p.about': 'About',
      'p.version': 'Version {v}',
      'p.storage': 'Storage used: {mb} MB',

      'year.name': 'Year {w}',
      'year.w1': '1',
      'year.w2': '2',
      'year.w3': '3',
      'year.w4': '4',
      'year.w5': '5',
      'year.w6': '6',
      'year.w7': '7',
      'year.w8': '8',
      'sem.name': 'Semester {n}',

      'st.current': 'Current',
      'st.done': 'Finished',
      'st.future': 'Upcoming',

      'dl.bachelor': 'Bachelor',
      'dl.master': 'Master',
      'dl.phd': 'PhD',

      'toast.saved': 'Saved',
      'toast.deleted': 'Deleted',
      'toast.storageFull': 'Storage is full — remove some note images',
      'toast.importedN': 'Imported: {t} tasks and {n} notes',
      'toast.importBad': 'Invalid file',
      'toast.langSet': 'Language changed',
      'toast.cloudSyncSuccess': 'Synced to cloud ☁️',
      'toast.cloudSyncFail': 'Sync failed — check your connection',
      'toast.cloudDisabled': 'Cloud sync disabled (Supabase not configured)',

      /* Cloud sync / auth */
      'cloud.title': 'Cloud Sync',
      'cloud.subtitle': 'Sign in with Google to back up your data and access it from any device.',
      'cloud.signIn': 'Sign in with Google',
      'cloud.signInDesc': 'Your local data will be uploaded automatically on first login and synced on every change.',
      'cloud.signedIn': 'Signed in as',
      'cloud.signOut': 'Sign out',
      'cloud.syncNow': 'Sync now',
      'cloud.syncing': 'Syncing…',
      'cloud.lastSync': 'Last sync: {time}',
      'cloud.neverSync': 'Never synced',
      'cloud.connected': 'Connected ☁️',
      'cloud.offline': 'Offline',
      'cloud.dataSafe': 'Your data is safe on this device even without a connection.',
      'cloud.mergeNote': 'Cloud and local data are merged automatically.',
      'cloud.deleteAccount': 'Delete account',
      'cloud.signOutConfirm': 'Sign out? Your data will stay on this device but sync will stop.',
      'cloud.deleteAccountConfirm': 'Permanently delete account? All your data will be erased. This cannot be undone.',
      'cloud.deleteAccountError': 'Failed to delete account',
      'cloud.loginTitle': 'Sign in to continue',
      'cloud.loginHint': 'Sign in with Google to sync and back up your data.',
      'cloud.loginBtn': 'Sign in with Google',
      'cloud.loginError': 'Sign-in failed — try again',
      'auth.subtitle': 'Sign in to back up your data and sync it across devices',
      'auth.signIn': 'Continue with Google',
      'auth.hint': 'Your data is safely stored in your account — it will never be lost',
      'auth.fail': 'Sign-in failed — please try again',

      /* Motivational messages */
      'mo.great': "Great job! You're on track 🎓",
      'mo.allDone': "Awesome! All today's tasks are done ✨",
      'mo.keepGoing': 'Keep going — almost there 💪',
      'mo.start': 'Start your day with the first task!',
      'mo.noTasks': 'Enjoy your day — no tasks today 🌤️',
      'mo.statsHigh': 'Excellent performance — keep it up! 🏆',
      'mo.statsMid': 'Good job — just a few steps left! 📚',
      'mo.statsLow': 'No worries — every step gets you closer! 🌱',

      /* Streaks */
      'str.label': 'Day Streak',
      'str.days': '{n} days',

      /* Places extra */
      'pl.lat': 'Latitude',
      'pl.lng': 'Longitude',
      'pl.noPlaces': 'No saved places yet. Add your first one!',
      'pl.latLngRequired': 'Please provide Latitude and Longitude',
      'pl.openExt': 'Open in Yandex Maps',
      'pl.count': '{n} places',
      'pl.filterPh': 'Search your places… (name, note, coordinates)',
      'pl.view': 'View on map',
      'pl.copyCoords': 'Copy coordinates',
      'pl.copied': 'Coordinates copied',
      'pl.searchLabel': 'Pinpoint the location',
      'pl.searchPh': 'Search an address or paste coordinates (24.71, 46.67)',
      'pl.noResults': 'No results',
      'pl.searching': 'Searching…',
      'pl.searchFail': 'Search failed — check your connection',
      'pl.parsed': 'Use these coordinates',
      'pl.mapOffline': 'Yandex Maps unavailable — switched to OpenStreetMap',
  'pl.mapError': 'Could not load map tiles — check your connection or disable the ad-blocker for this site and retry',
  'pl.retry': 'Retry',
    },
  };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LANGS: SL.LANGS, STRINGS: SL.STRINGS };
  }
})(typeof window !== 'undefined' ? window : globalThis);
